### PR TITLE
Improvements to dependency management

### PR DESCRIPTION
**Pull request by tgross**
This PR tries to make the dependency management story easier to understand while still allowing our upcoming subpackages to be "go gettable" for https://github.com/joyent/containerbuddy/issues/83. This also assists me in prepping for https://github.com/joyent/containerbuddy/issues/27.

The specific changes are:
- Eliminated the second makefile for inside the container, which I found hard to debug because of redundant env vars.
- Add `add-dep` makefile target that will use go get to fetch the dependency and record it via Godeps `save` function; this makes it easier to add new dependencies correctly.

The new `add-dep` target works like this in practice:

```bash
DEP=github.com/prometheus/client_golang/prometheus PKG=metrics make add-dep
docker run --rm \
            -v /Users/tim.gross/src/tgross/containerbuddy:/go/cb \
                -v /Users/tim.gross/src/tgross/containerbuddy:/go/cb/src \
                -e GOPATH=/go/cb/src/metrics \
                -w /go/cb/src/metrics \
                containerbuddy_build go get github.com/prometheus/client_golang/prometheus
docker run --rm \
            -v /Users/tim.gross/src/tgross/containerbuddy:/go/cb \
                -v /Users/tim.gross/src/tgross/containerbuddy:/go/cb/src \
                -e GOPATH=/go/cb/src/metrics \
                -w /go/cb/src/metrics \
                containerbuddy_build godep save
mv metrics/src metrics/vendor
```

cc @justenwalker @misterbisson

### CODE REVIEW

**Comment by tgross** [comment]
Oops... I appear to have broken it during cleanup. Lemme fix.

**Comment by tgross** [comment]
Ok, after a couple of dumb mistakes and a rebase to hide the bodies, this should be good-to-go. :grinning:

**Comment by misterbisson** [comment]
LGTM.

@justenwalker are you following along with these changes?

:house_with_garden: :walking:

**Comment by justenwalker** [comment]
@misterbisson Yeah, I've been looking a them - haven't had much time to verify them locally but they LGTM

Very nice cleanup efforts @tgross !

**Pull request merged**
