### PR TITLE
Bump version to 0.0.3

### PR DESCRIPTION
**Pull request by tgross**
Also tweaked release makefile target to push tags to joyent/origin to make doing releases involve one less manual step.

cc @misterbisson to give this a LGTM so we can make a new release.

### CODE REVIEW

**Comment by justenwalker** [comment]
Noticed a bug with #20 and fixed it with #25.  If you're releasing a version, it might be good to get this in before this PR.

**Comment by tgross** [comment]
Will do, thanks @justenwalker

**Comment by tgross** [comment]
I ended up with some annoying spurious merge commits in this branch. I'm going to un-muss it up for cleanliness and close this PR.

**Comment by tgross** [comment]
Nevermind, my history is too muddy in this branch so fixing it up would be evil at this point.

**Pull request closed without merging**
