### PR TITLE
Fixes #50.

### LINKED ISSUE #50: Containerbuddy doesn't handle interfaces without an IP or with a dual IPV4/IPV6 address
On my local workstation, I have the following crazy amount of interfaces:

```
docker0   Link encap:Ethernet  HWaddr 02:42:27:ff:b2:cc  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:27ff:feff:b2cc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:128306 errors:0 dropped:0 overruns:0 frame:0
          TX packets:158590 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:8752297 (8.7 MB)  TX bytes:483052292 (483.0 MB)

eth0      Link encap:Ethernet  HWaddr 10:c3:7b:45:a2:ff  
          inet addr:192.168.0.7  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::12c3:7bff:fe45:a2ff/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5764724 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2369492 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:5741557978 (5.7 GB)  TX bytes:390985056 (390.9 MB)
          Interrupt:18 Memory:fbf00000-fbf20000 

eth1      Link encap:Ethernet  HWaddr 40:16:7e:37:99:a6  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:19 Memory:fb800000-fb820000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:353966 errors:0 dropped:0 overruns:0 frame:0
          TX packets:353966 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:57731938 (57.7 MB)  TX bytes:57731938 (57.7 MB)

lxcbr0    Link encap:Ethernet  HWaddr 7a:01:23:0a:6a:1f  
          inet addr:10.0.3.1  Bcast:10.0.3.255  Mask:255.255.255.0
          inet6 addr: fe80::7801:23ff:fe0a:6a1f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:18425 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:3809150 (3.8 MB)

veth9a44ba0 Link encap:Ethernet  HWaddr 3e:fb:89:da:76:7f  
          inet6 addr: fe80::3cfb:89ff:feda:767f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8 errors:0 dropped:0 overruns:0 frame:0
          TX packets:33 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:648 (648.0 B)  TX bytes:7584 (7.5 KB)

vmnet1    Link encap:Ethernet  HWaddr 00:50:56:c0:00:01  
          inet addr:10.99.99.1  Bcast:10.99.99.255  Mask:255.255.255.0
          inet6 addr: fe80::250:56ff:fec0:1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:160348 errors:0 dropped:16648 overruns:0 frame:0
          TX packets:18424 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vmnet8    Link encap:Ethernet  HWaddr 00:50:56:c0:00:08  
          inet addr:10.88.88.1  Bcast:10.88.88.255  Mask:255.255.255.0
          inet6 addr: fe80::250:56ff:fec0:8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:222122 errors:0 dropped:16648 overruns:0 frame:0
          TX packets:240397 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 00:24:01:ee:dc:bc  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

If you look at `eth1`, you can see that nothing is plugged into it, so its IP addresses will be empty.

### PR DESCRIPTION
**Pull request by dekobon**
I've been trying to execute the unit tests on my local workstation outside of the docker build environment. The tests were failing on IP parsing. Since this would be a quick fix, I went ahead and made the changes. Please tell me what you think.

### CODE REVIEW

**Comment by tgross** [comment]
LGTM once you add some tests, @dekobon. But...

> I've been trying to execute the unit tests on my local workstation outside of the docker build environment.

...I feel like that shouldn't necessarily be supported. The reason we use Docker as the build platform is to avoid having to support every local configuration in existence; Golang developers in particular have a bad habit of making all kinds of assumptions about `GOPATH` and dependency management that we really don't want to get into.

**Comment by justenwalker** [comment]
Interesting, so it groups IPV4 and IPV6 addressed together.  

@tgross - Maybe I'm over thinking this, but; Golang docs don't document this behavior. I hope we aren't relying something undocumented about the order in which these IPs are returned.

Should we instead split & [parse these addresses](https://golang.org/pkg/net/#ParseCIDR) and explicitly pick the one which is IPV4? Should we have a flag to prefer IPV4 over IPV6?

**Comment by misterbisson** [comment]
> Should we have a flag to prefer IPV4 over IPV6?

@justenwalker and @tgross: do we need to ticket an issue to add IPv6 support to Containerbuddy (and for users to specify their preference)?

**Comment by dekobon** [comment]
You can peek at what golang is doing here: https://golang.org/src/syscall/netlink_linux.go

Also, it looks like we are in good company about IPV6 confusion: https://github.com/hashicorp/consul/issues/529

**Comment by tgross** [comment]
Ensuring we have IPv6 support is likely to be a bit of extra effort to make sure we're not making IPv4 assumptions elsewhere in the code. Here's what I recommend:

- For this issue let's force the case of a IPv4/6 interface to select the IPv4 IP address by parsing the addresses as @justenwalker has suggested.
- And then let's open a new ticket per @misterbisson's suggestion to provide IPv6 support so that we can review the whole code base in that light.

**Comment by tgross** [comment]
This LGTM. I've opened https://github.com/joyent/containerbuddy/issues/52 for further discussion of the IPv6 issue.

**Pull request merged**
